import numpy as np
import matplotlib.pyplot as plt
data=np.random.normal(100,5,1000)
mle.mean=np.mean(data)
mle.var=np.var(data)
print(f"MLE Mean={mle.mean:.2f}")
print(f"MLE Variance={mle.var:.2f}")
plt.figure(figsize=(8,6))
plt.hist(data,bins=30,density=True,alpha=0.6,color='skyblue',edgecolor='black')
plt.axvline(mle.mean,color='red',linestyle='--',linewidth=2,label=f'MLE Mean={mle.mean:.2f}')
plt.xlabel('Value')
plt.ylabel('Density')
plt.title('MLE Simulation for normal distribution')
plt.legend()
plt.grid(True,alpha=0.3)
plt.savefig('mle.plot.png',dpi=150)
print("mle.plot.png")
